sched/fair: fix reweight_task() declaration and definition
The CFS scheduler was failing to build due to:

  error: implicit declaration of function 'reweight_task'
  error: conflicting types for 'reweight_task'
  error: too many arguments to function call, expected 3, have 4

This patch fixes it by:
- Adding a forward declaration for reweight_task()
- Defining reweight_task() with the correct signature
- Updating the call to reweight_entity() to pass 3 args instead of 4

With this change, fair.c builds cleanly again without implicit
declaration or argument mismatch errors.